apiVersion: apps/v1
kind: Deployment
metadata:
  name: plc
  labels:
    app: plc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plc
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: plc
    spec:
      containers:
        - name: openplc
          image: oonray/openplc:v1.1.0
          ports:
            - containerPort: 8080
