apiVersion: v1
kind: Service
metadata:
  name: plc
spec:
  type: ClusterIP
  selector:
    app: plc
  ports:
    - protocol: TCP
      name: plc
      port: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plc-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "plc.in.cluster.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plc
                port:
                  number: 8080
